# Generated by Django 4.2.6 on 2023-11-07 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_product_user_alter_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('address_region', models.CharField(blank=True, max_length=255)),
                ('address_city', models.CharField(blank=True, max_length=255)),
                ('address_street', models.CharField(blank=True, max_length=255)),
                ('address_home', models.CharField(blank=True, max_length=255)),
                ('address_lat', models.CharField(blank=True, max_length=255)),
                ('address_lon', models.CharField(blank=True, max_length=255)),
                ('address_map_district', models.CharField(blank=True, max_length=255)),
                ('address_map_link', models.TextField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.shop')),
            ],
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('weight_value', models.IntegerField(blank=True)),
                ('weight_measure', models.CharField(max_length=20)),
                ('images', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('dimensions_width', models.CharField(blank=True, max_length=255)),
                ('dimensions_height', models.CharField(blank=True, max_length=255)),
                ('dimensions_weight', models.CharField(blank=True, max_length=255)),
                ('dimensions_length', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.product')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='sub_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sup_product', to='product.subproduct'),
        ),
        migrations.AddField(
            model_name='product',
            name='advantages',
            field=models.ManyToManyField(blank=True, default=1, to='product.advantage'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, default=1, to='product.category'),
        ),
    ]
