# Generated by Django 4.2.6 on 2023-11-08 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_advantage_category_shop_stock_subproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_uuid', models.CharField(max_length=255, unique=True)),
                ('total_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.cart', to_field='cart_uuid')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='advantage',
            options={'ordering': ('title',), 'verbose_name': 'Преимущество', 'verbose_name_plural': 'Преимущество'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('title',), 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренд'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='subproduct',
            options={'ordering': ('title',)},
        ),
        migrations.RenameField(
            model_name='subproduct',
            old_name='stock',
            new_name='stock_item',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subproduct',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sub_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.subproduct'),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='subproduct',
            index_together={('id', 'slug')},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed', models.BooleanField(default=False)),
                ('payment_uuid', models.CharField(blank=True, max_length=255, unique=True)),
                ('order_uuid', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartItem', to='product.cartitem')),
                ('cart_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart', to='product.cart', to_field='cart_uuid')),
                ('order_status', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orderStatus', to='product.orderstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='order_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.order', to_field='order_uuid'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sub_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.subproduct'),
        ),
    ]
