# Generated by Django 4.2.6 on 2023-11-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_cart_cartitem_orderstatus_alter_advantage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Товар в корзине', 'verbose_name_plural': 'Товар в корзине'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказ'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'ordering': ('title',), 'verbose_name': 'Статус заказа', 'verbose_name_plural': 'Статус заказа'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('title',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукт'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ('title',), 'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазин'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склад'},
        ),
        migrations.AlterModelOptions(
            name='subproduct',
            options={'ordering': ('title',), 'verbose_name': 'Подпродукт', 'verbose_name_plural': 'Подпродукт'},
        ),
    ]
