# Generated by Django 4.2.6 on 2023-11-08 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_advantage_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Мера',
                'verbose_name_plural': 'Меры',
            },
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='weight_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.measure'),
        ),
    ]
