# Generated by Django 4.2.6 on 2023-11-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_measure_alter_subproduct_weight_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
