# Generated by Django 4.2.6 on 2023-11-08 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_stock_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='order_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.order', to_field='order_uuid'),
        ),
    ]
