# Generated by Django 4.2.6 on 2023-11-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_cartitem_order_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_products',
            field=models.ManyToManyField(blank=True, to='product.subproduct'),
        ),
    ]
