# Generated by Django 4.2.6 on 2023-11-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_subproduct_product_product_sub_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart_uuid',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='order_uuid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_uuid',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_item',
            field=models.ManyToManyField(blank=True, to='product.cartitem'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_item',
            field=models.ManyToManyField(blank=True, to='product.cartitem'),
        ),
    ]
