# Generated by Django 4.2.6 on 2023-11-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_cartitem_cart_uuid_remove_cartitem_order_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_uuid',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
