# Generated by Django 4.2.6 on 2023-11-18 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='images',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orderStatus', to='product.orderstatus'),
        ),
    ]
